version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog.Service/Dockerfile
    environment:
      #- catalogdbsecret=Server=localhost,1433; Database=sql-server-db; User=sa; Password=micr0tunespass@word1;
      - aiinstrumkeysecret=85aac9fc-aa42-481e-8285-ba4494b9d501
      - sbconnstrsecret=Endpoint=sb://learn-activateazure.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=B8ckcCZKJA31xvmL/MmMQdkjhnimcKOMlksFqcNrsqw=;EntityPath=eventbustopic 
    depends_on:
      - sql-server-db

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "micr0tunespass@word1"
      ACCEPT_EULA: "Y"
