apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
data:
  aiinstrumkeysecret: NWU4YTY3ODctMDI3Ny00OGJkLTlkYWMtZjZkZTk1OGQ4NDRk # echo -n 5e8a6787-0277-48bd-9dac-f6de958d844d | base64
  sbconnstrsecret: c2Jjb25uc3Ryc2VjcmV0 # echo-n sbconnstrsecret | base64
  catalogdbsecret: U2VydmVyPXRjcDphY2EtZGVtLXNxbC5kYXRhYmFzZS53aW5kb3dzLm5ldCwxNDMzO0luaXRpYWwgQ2F0YWxvZz1hY2EtZGVtby1zcWxkYjtQZXJzaXN0IFNlY3VyaXR5IEluZm89RmFsc2U7VXNlciBJRD1taWNyMHR1bmVzc3FsbG9naW47UGFzc3dvcmQ9bWljcjB0dW5lc3Bhc3NAd29yZDE7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs= # echo -n Server=tcp:aca-dem-sql.database.windows.net,1433;Initial Catalog=aca-demo-sqldb;Persist Security Info=False;User ID=micr0tunessqllogin;Password=micr0tunespass@word1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; | base64
  

